name: Auto-linter

on: 
  push:
    paths: "*.py"

jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout/clone the code"
        uses: actions/checkout@v4

      # Step 2: Install and set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Specify your required Python version  

      - name: Install Linter
        run: pip install ruff

      - name: "Checking linter code"
        run: ruff check .
  
