name: Auto-linter

on: 
  push:
    paths: "*.py"

jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout/clone the code"
        uses: actions/checkout@v4

      - name: Install Linter
        run: pip install ruff

      - name: "Checking linter code"
        run: ruff check .
  
